import os
import sys
import anthropic
from dotenv import load_dotenv
from datetime import datetime

# === Load .env and Claude Setup ===
load_dotenv()
client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
model = os.getenv("ANTHROPIC_MODEL", "claude-sonnet-4-20250514")

# === Get target path ===
target_path = sys.argv[1] if len(sys.argv) > 1 else "."
output_dir = "docs"
os.makedirs(output_dir, exist_ok=True)

# Ensure .nojekyll exists for GitHub Pages
with open(os.path.join(output_dir, ".nojekyll"), "w") as f:
    pass

index_path = os.path.join(output_dir, "index.md")
index_entries = []

# === Walk all .py files recursively ===
py_files = []
for root, _, files in os.walk(target_path):
    for file in files:
        if file.endswith(".py") and not file.startswith("test_") and file != "__init__.py":
            py_files.append(os.path.join(root, file))

if not py_files:
    print("⚠️ No Python files found to document.")
    sys.exit(0)

print(f"📂 Found {len(py_files)} Python files to document.")

# === Loop through each file and document ===
for file_path in py_files:
    try:
        with open(file_path, "r") as f:
            source_code = f.read()

        rel_path = os.path.relpath(file_path, start=target_path).replace("/", "_").replace(".", "_")
        timestamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
        filename_md = f"autodoc_{rel_path}_{timestamp}.md"
        out_path = os.path.join(output_dir, filename_md)

        prompt = f'''You are a technical writer. Please generate professional, clear documentation in Markdown format for the following Python code:

```python
{source_code}
```'''

        response = client.messages.create(
            model=model,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}]
        )

        markdown = response.content[0].text.strip()

        header = (
            f"<!--\n"
            f"This documentation was auto-generated by Claude on {timestamp}.\n"
            f"Source file: {file_path}\n"
            f"-->\n\n"
        )

        with open(out_path, "w") as out_file:
            out_file.write(header + markdown)

        print(f"✅ Documented: {file_path} → {out_path}")
        index_entries.append(f"- [{file_path}](./{filename_md})")

    except Exception as e:
        print(f"❌ Error documenting {file_path}: {e}")

# === Write index.md ===
with open(index_path, "w") as index_file:
    index_file.write("# 📚 Auto-Generated Documentation Index\n\n")
    index_file.write("\n".join(index_entries))

print(f"📘 Index created at: {index_path}")