name: Auto-Generate Docs

on:
  push:
    branches:
      - main

jobs:
  autodoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: pip install anthropic python-dotenv
      - name: Run autodoc script
        run: python tools/autodoc.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_MODEL: ${{ secrets.ANTHROPIC_MODEL }}
