name: Auto-Generate Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'            # ← triggers only when files in docs/ change
  workflow_dispatch:         # Optional: manual trigger
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  autodoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
            pip install anthropic python-dotenv 
            pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python

      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force

      - name: Run autodoc script
        run: python tools/autodoc.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_MODEL: ${{ secrets.ANTHROPIC_MODEL }}

      - name: Commit & Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git diff --cached --quiet || git commit -m "🤖 Auto-update docs via Nautee"
          git push